export const SERVICE_TOKENS = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  POST_SERVICE: 'POST_SERVICE',
  ANNOUNCEMENT_SERVICE: 'ANNOUNCEMENT_SERVICE',
  SURVEY_SERVICE: 'SURVEY_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  FILE_SERVICE: 'FILE_SERVICE',
} as const;
